### ISSUE TITLE
Export all reflections or/and memories

### ISSUE THREAD

**Issue by mizu-048** [xp4u1/memoria#11]
in txt, md, etc 
whichever is best suited for this

(in a single or mulitple files for each entry in the data base)

also option for periodic backups to a custom location

**Comment by xp4u1** [comment]
That would be quite easy to implement with a CouchDB client. Just sync your Memoria app with CouchDB, which stores all the entries in a JSON-like format. Your problem could be solved with a standalone application or script that parses the CouchDB data and generates a Markdown file for each entry.

Periodic backups shouldn't be a problem in the next version. I've implemented a live sync feature, which will be released with the next update (see #10). If you want periodic updates in a text file format, you could create a cron job on your server with CouchDB that runs scheduled backups.

**Comment by mizu-048** [comment]
the thing is i don't understand properly understand what couchdb is, seems to be for syncronization and stuff

i asked for period backup in a custom folder since i use syncthing to sync a backup folder with my desktop to keep such stuff safe.

from what i understand i would need the couchdb server to be running to backup my data or export it while in my approah i wish to have it backup independantly which i can sync whenever i have time to run syncthjng on both devices

**Comment by xp4u1** [comment]
I want to focus on the CouchDB sync. Exporting as files is not trivial to implement with Ionic/Capacitor, but it should be fairly easy to do in an external application that connects to CouchDB.

I’m sorry, but I don’t have enough time to implement your feature request right now. I want to prioritize improving memoria’s core features.
